spring.application.name=weatherapi
server.port=8080

# Cache TTL in seconds (10 minutes)
weather.cache.ttl=600

# Logging
logging.level.com.ashwin.weatherapi=INFO
logging.level.org.springframework.cache=TRACE

# API Keys
tomorrow.io.api.key=0A6XnL9Vte7ODnhn3WpZwuN77iKbc8QR
weather.api.com.api.key=2f4ee196edfd4c57ae0130715252609

# Rate Limiting
# Rate limit requests per window it is high beacuse for swagger ui testing
rate.limit.requests=50
rate.limit.window.seconds=5
